# Generated by Django 3.0 on 2020-08-05 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roshita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro_title', models.CharField(max_length=150)),
                ('ro_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
