# Generated by Django 3.0 on 2020-08-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roshita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roshita',
            old_name='ro_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='roshita',
            old_name='ro_title',
            new_name='title',
        ),
    ]
